---
title: "myTAI"
output: rmarkdown::md_document
---

<br/><br/>

<br/><br/>

<br/><br/>

<p style="font-family: 'Fira Mono', monospace; font-size: 2.5rem;">
**myTAI** unlocks statistically-informed analysis of evolutionary signals hidden in the gene expression data (transcriptome)
</p>

<br/><br/>

<br/><br/>

<br/><br/>

```{r message = FALSE, fig.height=3, fig.width=4, fig.alt="plot_signature_output", dev.args = list(bg = 'transparent'), fig.align='center'}
library(myTAI)
# obtain an example phylo-expression object
data("example_phyex_set")
# plot away!
myTAI::plot_signature(example_phyex_set)  
```

<br/><br/>

<br/><br/>

<br/><br/>

<br/><br/>

<br/><br/>

<p style="font-family: 'Fira Mono', monospace; font-size: 1.5rem;">
Initially inspired by the need to statistically evaluate the 'molecular hourglass' pattern that linked transcriptome evolution to 19th-century embryo studies, the original myTAI package has since evolved to facilitate fast and robust analysis of *any* transcriptome evolution patterns, from embryo development^[some early studies include [Kalinka et al. (2010) Nature](https://www.nature.com/articles/nature09634), [Domazet-Lošo & Tautz (2010) Nature](https://www.nature.com/articles/nature09632), [Quint et al. (2012) Nature](https://www.nature.com/articles/nature11394)] to cancer progression and drug perturbation experiments.
</p>

<br/><br/>

<br/><br/>

---

## What can `myTAIv2` do?

<p style="font-family: 'Fira Mono', monospace; font-size: 1.5rem;">
⚡ `Ultra-fast computations` → rapid permutation tests that scales to single-cell genomics.  
🦾 `Moved on from traditional R data structures to modern S7 classes` → optimised handling of large 'phylo-expression' datasets.  
🔨 `Break your hourglass` → uncover the genes driving your transcriptome evolution patterns.  
⌛ `Aesthetic plots` → publication-ready information-rich figures!  
</p>

<br/><br/>

<p style="font-family: 'Fira Mono', monospace; font-size: 2rem;">
Get started with myTAI → <a href="articles/myTAI.html" class="btn btn-outline-light" style="font-family: 'Fira Mono', monospace; font-size: 2rem;"> 🍹 </a>
</p>

---

<br/><br/>

<br/><br/>

<br/><br/>

<br/><br/>

<p style="font-family: 'Fira Mono', monospace; font-size: 1.5rem;">
Cite myTAI for your own research. 
</p>

<p style="font-family: 'Fira Mono', monospace; font-size: 1.5rem;">
> Drost et al. __myTAI: evolutionary transcriptomics with R__. _Bioinformatics_ 2018, 34 (9), 1589-1590. [doi:10.1093](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btx835/4772684)
</p>

<p style="font-family: 'Fira Mono', monospace; font-size: 1.5rem;">
And follow [`@DrostLab`](https://drostlab.com/) for more bioinformatics and digital biology software solutions.
</p>

<br/><br/>

<br/><br/>
