# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rcpp_tei_parallel
#' @name rcpp_tei_parallel
#' @description computes the phylogenetically based
#' transcriptome evolutionary index (TEI)
#' @return list
#' @param expression ExpressionSet as sparseMatrix
#' @param ps named Phylostratum
#' @param ncores number of cores
#' @examples
#' ## load example sequence data
#' data("PhyloExpressionSetExample", package="myTAI")
#' spmat <- as(data.matrix(PhyloExpressionSetExample[,-c(1,2)]), "sparseMatrix")
#' rownames(spmat) <- PhyloExpressionSetExample$GeneID
#' ps <- setNames(PhyloExpressionSetExample$Phylostratum, PhyloExpressionSetExample$GeneID)
#' rcpp_tei_parallel(spmat, ps)
NULL

cpp_TAI <- function(ExpressionSet, Phylostratum) {
    .Call(`_myTAI_cpp_TAI`, ExpressionSet, Phylostratum)
}

cpp_bootMatrix <- function(ExpressionMatrix, AgeVector, permutations) {
    .Call(`_myTAI_cpp_bootMatrix`, ExpressionMatrix, AgeVector, permutations)
}

cpp_pMatrix <- function(ExpressionSet, AgeVector) {
    .Call(`_myTAI_cpp_pMatrix`, ExpressionSet, AgeVector)
}

cpp_std_error <- function(x) {
    .Call(`_myTAI_cpp_std_error`, x)
}

cpp_geom_mean <- function(x) {
    .Call(`_myTAI_cpp_geom_mean`, x)
}

cpp_harmonic_mean <- function(x) {
    .Call(`_myTAI_cpp_harmonic_mean`, x)
}

cpp_omitMatrix <- function(ExpressionSet, AgeVector) {
    .Call(`_myTAI_cpp_omitMatrix`, ExpressionSet, AgeVector)
}

#' @author Kristian K Ullrich
rcpp_tei_parallel <- function(expression, ps, ncores = 1L) {
    .Call(`_myTAI_rcpp_tei_parallel`, expression, ps, ncores)
}

