# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cpp_TAI <- function(ExpressionSet, Phylostratum) {
    .Call('myTAI_cpp_TAI', PACKAGE = 'myTAI', ExpressionSet, Phylostratum)
}

#' @export
cpp_bootMatrix <- function(ExpressionMatrix, AgeVector, permutations) {
    .Call('myTAI_cpp_bootMatrix', PACKAGE = 'myTAI', ExpressionMatrix, AgeVector, permutations)
}

#' @export
cpp_pMatrix <- function(ExpressionSet, AgeVector) {
    .Call('myTAI_cpp_pMatrix', PACKAGE = 'myTAI', ExpressionSet, AgeVector)
}

#' @export
cpp_std_error <- function(x) {
    .Call('myTAI_cpp_std_error', PACKAGE = 'myTAI', x)
}

#' @export  
cpp_geom_mean <- function(x) {
    .Call('myTAI_cpp_geom_mean', PACKAGE = 'myTAI', x)
}

#' @export
cpp_omitMatrix <- function(ExpressionSet, AgeVector) {
    .Call('myTAI_cpp_omitMatrix', PACKAGE = 'myTAI', ExpressionSet, AgeVector)
}

