name: R-CMD-check

on:
  push:
    branches: [main, stefan-refactor]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest }
          - { os: macos-latest }
          - { os: windows-latest }

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Check
        uses: r-lib/actions/check-r-package@v2